from rest_framework import serializers
from .models import Module, Exam, Assignment, StudyTask

## Serializers for the core models

# -------------------------
# MODULE SERIALIZER
# -------------------------
class ModuleSerializer(serializers.ModelSerializer):
    class Meta:
        model = Module
        fields = ["id", "module_code", "title", "semester"]
        read_only_fields = ["id", "student"] # ID is read-only because it's auto-generated by the database

# -----------------------------
# EXAMS serializer
# -----------------------------
class ExamSerializer(serializers.ModelSerializer):
    class Meta:
        model = Exam
        fields = ["id", "module", "exam_date", "location", "notes"]
        read_only_fields = ["id"]

# -----------------------------
# ASSIGNMENT SERIALIZER
# -----------------------------
class AssignmentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Assignment
        fields = ["id", "module", "title", "due_date", "status", "weight"]
        read_only_fields = ["id"]


# -----------------------------
# STUDY TASK SERIALIZER
# -----------------------------
class StudyTaskSerializer(serializers.ModelSerializer):
    class Meta:
        model = StudyTask
        fields = ["id", "module", "title", "target_date", "duration_minutes", "is_completed"]
        read_only_fields = ["id"]
